# Service deployment yml file configuration
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-management-deployment
  namespace: test
  labels:
    app: data-management-deployment
spec:
  replicas: 1 # number of pods
  selector:
    matchLabels:
      app: data-management-deployment
  template:
    metadata:
      labels:
        app: data-management-deployment
    spec:
      containers:
        - name: data-management-container
          image: gcr.io/clus-demo/data-management-default-1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: CLIENT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: sftp-service-secret
                  key: CLIENT_EMAIL
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: sftp-service-secret
                  key: CLIENT_ID
            - name: PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: sftp-service-secret
                  key: PRIVATE_KEY
            - name: PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: sftp-service-secret
                  key: PROJECT_ID
            - name: TOKEN_URL
              valueFrom:
                secretKeyRef:
                  name: sftp-service-secret
                  key: TOKEN_URL
            - name: allFileExtension
              valueFrom:
                secretKeyRef:
                  name: sftp-service-secret
                  key: allFileExtension
            - name: apiURL
              valueFrom:
                secretKeyRef:
                  name: sftp-service-secret
                  key: apiURL
            - name: bucketName
              valueFrom:
                secretKeyRef:
                  name: sftp-service-secret
                  key: bucketName
            - name: destinationPath
              valueFrom:
                secretKeyRef:
                  name: sftp-service-secret
                  key: destinationPath
            - name: ftpServerPath
              valueFrom:
                secretKeyRef:
                  name: sftp-service-secret
                  key: ftpServerPath
            - name: HOST
              valueFrom:
                secretKeyRef:
                  name: sftp-service-secret
                  key: HOST
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: sftp-service-secret
                  key: PORT
            - name: USER
              valueFrom:
                secretKeyRef:
                  name: sftp-service-secret
                  key: USER
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sftp-service-secret
                  key: PASSWORD
            - name: SECURE
              valueFrom:
                secretKeyRef:
                  name: sftp-service-secret
                  key: SECURE
            - name: API_PORT
              valueFrom:
                secretKeyRef:
                  name: sftp-service-secret
                  key: API_PORT
            - name: API_ROOT
              valueFrom:
                secretKeyRef:
                  name: sftp-service-secret
                  key: API_ROOT
            - name: API_VERSION
              valueFrom:
                secretKeyRef:
                  name: sftp-service-secret
                  key: API_VERSION
            - name: API_HOST
              valueFrom:
                secretKeyRef:
                  name: sftp-service-secret
                  key: API_HOST
---
apiVersion: v1
kind: Service
metadata:
  name: data-management-service
  namespace: test
spec:
  type: NodePort
  selector:
    app: data-management-deployment
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30104
